version: '3'
services:
  api_groups:
    image: api-groups-project
    ports:
      - 4010:3000
    environment:
      PORT: 3000
      NODE_ENV: production
      ROOT_DIR: /service
      MONGO_DB_URL: mongodb://host.docker.internal:27017/sso
      PUBLIC_URL: ${PUBLIC_URL}